import {renderVersions} from './versions.mjs';
import {renderGraph} from "./graph.mjs";
import fs from 'node:fs';
const policies=JSON.parse(fs.readFileSync('src/data/policies.json'));const relations=JSON.parse(fs.readFileSync('src/data/policy-relations.json'));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>'/policies/'+p.id.toLowerCase(); const byId=id=>policies.find(p=>p.id===id);
const ext=(u,label)=>u?`<a class="external" href="${E(u)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:'';
const tone=p=>p.level==='国家'?'national':p.level==='上海'?'shanghai':'regional';
const badge=p=>`<span class="badge ${tone(p)}">${E(p.level)}</span><span class="status ${['待核验','征求意见','编制中','待补全文'].includes(p.status)?'pending':''}">${E(p.status)}</span>`;
const card=p=>`<article class="policy-card" data-id="${p.id}"><div class="card-top">${badge(p)}<span class="category">${E(p.category)}</span></div><h3><a href="${url(p)}">${E(p.title)}${p.document_no?`（${E(p.document_no)}）`:""}</a></h3><p class="issuer">${E(p.issuer)}</p><p class="summary">${E(p.one_line_summary)}</p><div class="tags">${p.keywords.slice(0,4).map(k=>`<span>#${E(k)}</span>`).join('')}</div><div class="card-bottom"><a href="${url(p)}">阅读政策 <span>→</span></a>${ext(p.official_url,p.official_label||'官方原文')}</div>${p.missing_source_reason?`<p class="missing-source"><strong>官方全文待补：</strong>${E(p.missing_source_reason)}</p>`:''}</article>`;
const nav=`<a class="brand" href="/"><span>华东分公司运营中心<span class="brand-sub">上海政策学习地图</span></span></a><nav aria-label="主导航"><a href="/" data-nav="map">政策地图</a><a href="/policies" data-nav="list">全部政策</a><a href="/about" data-nav="about">数据说明</a></nav><a class="repo-link" href="https://github.com/JJY085/HnhdYyzx-sh-policy" target="_blank" rel="noopener noreferrer">GitHub ↗</a>`;
const shell=(title,desc,body,active='')=>`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(title)} · 上海电力市场政策学习地图</title><meta name="description" content="${E(desc)}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script><script src="/learning.js" defer></script><script src="/graph.js" defer></script></head><body data-active="${active}"><a class="skip" href="#main">跳至正文</a><header>${nav}</header><main id="main">${body}</main><footer><span>上海电力市场政策学习地图</span><span>学习摘要以官方原文为准 · 数据整理 2026.09.15</span><a href="/about">来源与核验说明 ↗</a></footer></body></html>`;
const node=(id,name)=>`<a class="map-node ${tone(byId(id))}" href="${url(byId(id))}"><span>${name}</span><small>${E(byId(id).category)} ↗</small></a>`;
const map=`<section class="map-panel" aria-labelledby="map-title"><div class="panel-heading"><div><h2 id="map-title">从全国规则，到上海实践</h2><p>点击节点阅读政策，沿层级理解市场制度</p></div><div class="legend"><span>● 国家</span><span>● 区域</span><span>● 上海</span></div></div><div class="map-body"><div class="map-layer"><div class="layer-label"><b>01</b><strong>国家基础</strong><small>统一市场 · 1 + 6</small></div><div class="layer-content"><div class="root-node">${node('POLICY-N001','电力市场运行基本规则')}</div><div class="connector">↓</div><div class="node-row">${node('POLICY-N002','中长期市场')}${node('POLICY-N003','现货市场')}${node('POLICY-N004','辅助服务市场')}</div><div class="support-row">${node('POLICY-N005','市场注册')}${node('POLICY-N006','信息披露')}${node('POLICY-N007','计量结算')}</div><p class="map-group-label">顶层政策与建设指引</p><div class="support-row">${node('POLICY-N010','统一市场建设')}${node('POLICY-N009','市场监管')}${node('POLICY-N011','现货建设指引')}</div></div></div><div class="map-layer"><div class="layer-label"><b>02</b><strong>区域协同</strong><small>华东 / 长三角</small></div><div class="layer-content"><div class="connector">↓ 区域衔接</div><div class="node-row">${node('POLICY-EC001','跨省中长期')}${node('POLICY-EC002','辅助服务管理')}${node('POLICY-EC003','新能源消纳互济')}</div></div></div><div class="map-layer"><div class="layer-label"><b>03</b><strong>上海细则</strong><small>本地实施 · 专项政策</small></div><div class="layer-content"><div class="connector">↓ 本地实施</div><div class="node-row">${node('POLICY-SH002','上海中长期')}${node('POLICY-SH001','上海现货')}${node('POLICY-SH004','新能源入市')}</div><div class="support-row">${node('POLICY-SH003','现货限价')}${node('POLICY-SH005','绿色电力')}${node('POLICY-PENDING-001','调频规则 · 编制中')}</div><p class="map-group-label">年度安排与新型主体</p><div class="support-row">${node('POLICY-SH008','2026年度交易')}${node('POLICY-SH009','新型储能')}${node('POLICY-SH011','虚拟电厂')}</div><div class="support-row">${node('POLICY-SH010','调节能力奖励')}${node('POLICY-SH012','运营规范 · 待补全文')}</div></div></div></div><div class="map-foot">层级示意用于学习导航；具体上下位与关联关系见政策详情。<a href="/policies">查看全部 ${policies.length} 项政策 →</a></div></section>`;
const select=(name,label,values)=>`<label>${label}<select name="${name}"><option value="">全部${label}</option>${values.map(v=>`<option>${E(v)}</option>`).join('')}</select></label>`;
const unique=k=>[...new Set(policies.flatMap(p=>k==='category'?(p.categories||[p.category]):p[k]||[]))];
const learning=renderGraph(policies,relations,E,badge,url);
const library=`<section id="library" class="library"><div class="section-heading"><div><span class="eyebrow">POLICY LIBRARY</span><h2>政策关系网络 <span id="result-count">${policies.length}</span></h2></div><p>从政策节点出发，探索文件之间的联系</p></div><div class="library-views" aria-label="资料库视图"><a href="?view=map#library" id="view-map">政策关系网络</a><a href="?view=all#library" id="view-all">全部卡片</a></div>${learning}<div id="all-view"><form id="filters"><div class="search-wrap"><span aria-hidden="true">⌕</span><input id="search" name="q" type="search" aria-label="搜索政策" placeholder="搜索政策名称、发布机构、文号或关键词"><kbd>/</kbd></div><div class="filter-row">${select('level','规则层级',unique('level'))}${select('category','政策类型',unique('category'))}${select('subject','市场主体',unique('subjects'))}${select('status','状态',unique('status'))}${select('year','发布年份',[...new Set(policies.map(p=>p.publish_date?.slice(0,4)).filter(Boolean))].sort().reverse())}<button type="reset" class="reset">重置筛选</button></div></form><p class="result-message" aria-live="polite" id="result-message">共 ${policies.length} 项政策</p><div class="cards" id="cards">${policies.map(card).join('')}</div><div id="empty" hidden><h3>没有找到匹配的政策</h3><p>试试减少筛选条件，或换一个关键词。</p><button id="empty-reset">清除全部筛选</button></div></div></section>`;
const hero=`<section class="intro"><div><span class="eyebrow">SHANGHAI POWER MARKET / POLICY ATLAS</span><h1>上海市电力市场建设细则，宏观文件参考下方链接</h1><div class="macro-reference"><a class="macro-button" href="https://ericzhang-ouc.github.io/eric-competition-notes/policy-map.html" target="_blank" rel="noopener noreferrer">查看宏观政策地图 <span aria-hidden="true">↗</span></a><small>在新标签页打开</small></div></div><div class="intro-stats"><b>${policies.length}<small>政策条目</small></b><b>1+6<small>国家基础规则</small></b><b>3<small>学习层级</small></b></div></section>`;
const topics=[['上海现货','现货市场','上海'],['上海中长期','中长期市场','上海'],['辅助服务','辅助服务',''],['新能源入市','新能源',''],['绿色电力','绿色电力',''],['长三角交易','','长三角'],['新型储能','新型储能','上海'],['虚拟电厂','虚拟电厂','上海'],['零售交易','零售交易','上海']];
const topicHtml=`<section class="topics" aria-label="分类入口">${topics.map(([t,c,l],i)=>`<a href="/policies?category=${encodeURIComponent(c)}&level=${encodeURIComponent(l)}"><span>0${i+1}</span>${t}<b>↗</b></a>`).join('')}</section>`;
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/policies',{recursive:true});fs.cpSync('public','dist',{recursive:true});
fs.writeFileSync('dist/index.html',shell('政策地图','从全国统一电力市场到上海现货、中长期与新能源的政策学习地图。',hero+map+topicHtml+library,'map'));
fs.writeFileSync('dist/policies/index.html',shell('全部政策','搜索与筛选上海电力市场相关政策。',`<section class="page-intro"><span class="eyebrow">EXPLORE THE RULES</span><h1>全部政策</h1><p>按层级、类型、市场主体和版本状态，找到需要的规则。</p></section>`+library,'list'));
const prose=t=>t?String(t).split('\n').filter(l=>l.trim()&&!/^---/.test(l)).map(l=>`<p>${E(l.replace(/^(?:[-•]\s+|\d+[.、]\s*)/, '').replace(/`/g,''))}</p>`).join(''):'<p class="unavailable">该项摘要尚未补齐，请查阅官方原文。</p>';
const section=(id,t,body)=>`<section class="detail-section" id="${id}"><h2>${t}</h2>${body}</section>`;
for(const p of policies){const linked=relations.filter(r=>r.source===p.id||r.target===p.id);const relHtml=linked.map(r=>{const other=byId(r.source===p.id?r.target:r.source);return `<a class="relation-link" href="${url(other)}"><span>${r.type==='related'?'关联政策':r.source===p.id?'下位 / 配套政策':'上位政策'}</span><strong>${E(other.title)}</strong><b>→</b></a>`}).join('');const fields=[['发布机构',p.issuer],['文号',p.document_no],['发布日期',p.publish_date],['成文日期',p.document_date],...(p.print_date?[['印发日期',p.print_date]]:[]),['实施日期',p.effective_date],['核验范围',p.verification]];let content=`<div class="breadcrumb"><a href="/">政策地图</a> / <a href="/policies">全部政策</a> / ${E(p.category)}</div><div class="detail-layout"><article><div class="detail-head"><div>${badge(p)}</div><h1>${E(p.title)}</h1><p class="lead">${E(p.one_line_summary)}</p><dl>${fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${E(v||'未确认')}</dd></div>`).join('')}</dl><div class="official-actions">${ext(p.official_url,p.official_label||'查看官方发布页')}${p.official_fulltext_url&&p.official_fulltext_url!==p.official_url?ext(p.official_fulltext_url,p.fulltext_label||'查看官方附件'):''}</div>${p.missing_source_reason?`<aside class="notice"><strong>官方链接缺失原因</strong><p>${E(p.missing_source_reason)}</p></aside>`:''}</div>${p.notes?`<aside class="notice">${E(p.notes)}</aside>`:''}<p class="source-note">正文为学习摘要。内容依据项目资料及所列官方来源整理，核验范围见上方说明；摘要不替代正式文件。</p>${renderVersions(p.version_history,E,ext)}${section('background','01 / 背景与意义',prose([p.background,p.significance].filter(Boolean).join('\n')))}${section('content','02 / 主要内容',prose(p.main_content))}${section('rules','03 / 核心规则',prose(p.core_rules))}${section('participants','04 / 与上海市场参与者的关系',prose(p.participant_relevance))}${section('relations','05 / 关联政策',relHtml||'<p>暂未建立政策关系。</p>')}${p.batch===2?section('sources','来源与核验',`<p>最近核验：${E(p.last_verified)}。${E(p.verification)}</p>${(p.reference_sources||[]).map(r=>ext(r.url,E(r.label))).join('')}${(p.verification_sources||[]).filter(u=>!(p.reference_sources||[]).some(r=>r.url===u)).map((u,i)=>ext(u,`核验来源 ${i+1}`)).join('')}`):''}${section('keywords','06 / 关键词',`<div class="tags">${p.keywords.map(k=>`<a href="/policies?q=${encodeURIComponent(k)}">#${E(k)}</a>`).join('')}</div>`)}${p.supersedes||p.superseded_by?section('versions','版本沿革',[p.supersedes,p.superseded_by].filter(Boolean).map(id=>`<a href="${url(byId(id))}">${E(byId(id).title)}</a>`).join('')):''}</article><aside class="toc"><span class="eyebrow">本页导览</span>${[...(p.version_history?.length?[['version-history','版本沿革与核心修改']]:[]),['background','背景与意义'],['content','主要内容'],['rules','核心规则'],['participants','参与者关系'],['relations','关联政策'],['keywords','关键词']].map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}<div class="toc-note">${E(p.id)}<br>最近核验：${E(p.last_verified||'待核验')}<br><a href="/about">了解核验方式 ↗</a></div></aside></div>`;fs.mkdirSync('dist'+url(p),{recursive:true});fs.writeFileSync('dist'+url(p)+'/index.html',shell(p.title,p.one_line_summary,content));}
fs.mkdirSync('dist/about',{recursive:true});fs.writeFileSync('dist/about/index.html',shell('数据说明','政策来源、版本与核验范围说明。',`<article class="about"><span class="eyebrow">SOURCES & METHODOLOGY</span><h1>让每一条规则有据可查。</h1><h2>数据与来源</h2><p>本网站共收录 ${policies.length} 项政策资料：首批21项，第二批新增8项（含1项待补全文的文件集合）。第二批按用户确认的删除线排除7项，重复年度方案合并收录；排除仅针对本批新增范围。仅使用政府部门及电力交易平台链接作为原文入口。</p><h2>核验范围</h2><p>“发布信息已核验”表示已核对发布页中的政策名称、文号或日期等信息，不代表每条学习摘要已经过逐条法律审查，也不等于确认没有后续修订。未确认的元数据显示“未确认”；缺少规范全文时明确说明原因，相关文件引用不作为规范全文入口。“已发布”仅说明已取得发布依据，不表示已排除后续修订。</p><h2>状态与版本</h2><p>征求意见稿、编制中的规则与正式文件使用不同状态。上海现货实施细则已依据提供的2026年第一次修订批复及附件核验，详情页保留历史版本及材料缺口。2025年第一次修订材料待补，尚未取得最新整合全文；“结算试运行”不代表已确认具体生效日期。其他政策可通过版本关系连接，历史内容不被自动覆盖。</p><h2>主体标签与关系图</h2><p>主体标签根据已有资料明确提到的主体整理，仅用于检索，不表示市场准入资格。首页为层级学习示意，详细政策关系来自项目资料，关联不等于直接法律授权。</p><h2>核验记录</h2><div class="audit-list">${policies.map(p=>`<a href="${url(p)}"><strong>${E(p.title)}</strong><span>${E(p.verification)} · ${E(p.last_verified||'待核验')}</span></a>`).join('')}</div></article>`,'about'));
fs.writeFileSync('dist/404.html',shell('页面未找到','页面不存在',`<section class="about"><h1>这条路径暂时没有政策。</h1><p>可以回到资料库继续查找。</p><a href="/policies">浏览全部政策 →</a></section>`));
fs.writeFileSync('dist/policies.json',JSON.stringify(policies));fs.writeFileSync('dist/robots.txt','User-agent: *\nAllow: /\n');console.log(`Built ${policies.length+3} pages`);

// Prefix local routes for project-site hosting; root hosting remains the default.
const base=(process.env.BASE_PATH||'').replace(/\/$/,'');
if(base&&!/^\/[A-Za-z0-9_-]+$/.test(base))throw new Error('BASE_PATH must be a single safe path segment');
for(const file of fs.readdirSync('dist',{recursive:true}).filter(f=>f.endsWith('.html'))){const path='dist/'+file;let html=fs.readFileSync(path,'utf8');html=html.replace(/(href|src)="\/(?!\/)([^"?#]*)([^\"]*)"/g,(_,attr,route,suffix)=>{if(route==='policies'||route==='about'||route.startsWith('policies/'))route=route.replace(/\/$/,'')+'/';return `${attr}="${base}/${route}${suffix}"`;});html=html.replace('<body data-active=',`<body data-base="${base}" data-active=`);fs.writeFileSync(path,html);}
fs.writeFileSync('dist/.nojekyll','');
